FROM turtlebot3_base:latest

# Install catkin tools
RUN apt-get update && apt-get install -y python3-catkin-tools

# Create an overlay Catkin workspace
RUN source /opt/ros/noetic/setup.bash \
 && mkdir -p /overlay_ws/src \
 && cd /overlay_ws \
 && catkin_init_workspace
COPY ./tb3_navigation/ /overlay_ws/src/tb3_navigation/
RUN source /opt/ros/noetic/setup.bash \
 && cd /overlay_ws \
 && catkin config --extend /turtlebot3_ws/devel \
 && catkin build -j4

# Set up the work directory and entrypoint
WORKDIR /overlay_ws